language: generic
services:
  - docker
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      script: swift package update && swift test
    - os: linux
      before_install:
        - cd swift-5.0-dnssd && docker build -t swift-5.0-dnssd . && cd ..
      script:
        - docker run -it --rm --name swift --security-opt seccomp=unconfined -v $PWD:/root/project -w /root/project swift-5.0-dnssd swift test
